development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: diary_release
  pool: 5
  username: root
  password: 
  host: localhost
  port: 3306


production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: diary_release
  pool: 5
  username: root
  password: 
  host: localhost 
  port: 3306
